# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fbd66fd5c764286e44fb20f9a6a7fb64c89cd75eb9da62bc2f69a3c11ab9685aecd10dab5c3748143636cc61394e91d3f118275c9af9beebb94cd6df66d163c

test:
  secret_key_base: 68b64ad94a8f6a459bc9ea6065d5cc21ee117db0cbf042a2e16b2b51a367f38e54598f08a952008162c03e4aafa48476516ff954b6d20e02d8b9f8f4f342fab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
